#!/bin/bash
# postinst script
#
#

## declare an array variable
arr=(
"/usr/local/bin/snap.bash"
"/etc/snap.conf/snap.bash.conf"
)

## now loop through the above array
for i in "${arr[@]}"
do
   echo "$i"
    chown root:root "$i"
    chmod 755 "$i"
done





